# Generated by Django 5.1.4 on 2025-01-26 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0010_sportsfieldlocation_price_per_hour"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="created_at",
        ),
        migrations.AddField(
            model_name="payment",
            name="field",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="locations.sportsfieldlocation",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(max_length=50),
        ),
    ]
