# Generated by Django 5.1.4 on 2025-01-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_remove_payment_created_at_payment_field_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(default="Pending", max_length=50),
        ),
    ]
