# Generated by Django 5.1.4 on 2025-01-26 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="helprequest",
            name="email",
        ),
        migrations.RemoveField(
            model_name="helprequest",
            name="name",
        ),
        migrations.AddField(
            model_name="helprequest",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="help_requests",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
