# Generated by Django 5.1.4 on 2025-01-20 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Guest",
        ),
    ]
