# Generated by Django 5.1.4 on 2025-01-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="name",
        ),
        migrations.AddField(
            model_name="event",
            name="title",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
