# Generated by Django 5.1.4 on 2025-01-27 08:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_remove_event_name_event_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
