"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ss2cmi2nz&m8$3*q+g^1kx$^02e7c0nt1b4dxv!!_v5#(f#p ^'# noqa

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# إعادة التوجيه بعد تسجيل الدخول
LOGIN_REDIRECT_URL = '/user/'  # صفحة لوحة المستخدم

# إعادة التوجيه بعد تسجيل الخروج
LOGOUT_REDIRECT_URL = '/'

# Application definition

INSTALLED_APPS = [
    'crispy_forms',
    'locations.apps.LocationsConfig',
    'payments.apps.PaymentsConfig',
    'pages.apps.PagesConfig',
    'guests.apps.GuestsConfig',
    'users.apps.UsersConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',# noqa

    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',# noqa

    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',# noqa

    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',# noqa

    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'myproject/static')
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# إعداد المسار الذي سيتم حفظ الصور فيه
MEDIA_URL = '/media/'  # الرابط الأساسي للوصول إلى الصور
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # خادم SMTP الخاص بـ Gmail
EMAIL_PORT = 587  # المنفذ المستخدم لـ TLS
EMAIL_USE_TLS = True  # استخدام TLS لتشفير الاتصال
EMAIL_HOST_USER = 'prewish24@gmail.com'  
EMAIL_HOST_PASSWORD = 'Bur@454545'  

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# settings.py
PAYPAL_MODE = 'sandbox' 
PAYPAL_CLIENT_ID = 'AeJeYSLvTwZTZcWBA0Dk7LIKWtFUx_xNd6Ci0_XwEH6fHbiMhuaPQrl9OUgJ1QdXow0daLF6-QVh0NEK' # noqa
PAYPAL_CLIENT_SECRET = 'EDUm0nbXemVzxYExQG31VjDoQPQnGVXqh4lw_Cs7PyNhg5IA6ZhTlewf3im3tAGvdKEOJuqoJDJpCORe' # noqa