# Generated by Django 5.1.4 on 2025-01-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="address",
        ),
        migrations.RemoveField(
            model_name="location",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="location",
            name="description",
        ),
        migrations.RemoveField(
            model_name="location",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
