# Generated by Django 5.1.4 on 2025-01-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "locations",
            "0002_remove_location_address_remove_location_created_at_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SportsFieldLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Field Name")),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("football", "Football"),
                            ("basketball", "Basketball"),
                            ("volleyball", "Volleyball"),
                            ("tennis", "Tennis"),
                        ],
                        max_length=20,
                        verbose_name="Field Type",
                    ),
                ),
                ("latitude", models.FloatField(verbose_name="Latitude")),
                ("longitude", models.FloatField(verbose_name="Longitude")),
                ("address", models.TextField(verbose_name="Address")),
            ],
            options={
                "verbose_name": "Sports Field Location",
                "verbose_name_plural": "Sports Field Locations",
                "ordering": ["name"],
            },
        ),
        migrations.DeleteModel(
            name="Location",
        ),
    ]
