# Generated by Django 5.1.4 on 2025-01-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0003_sportsfieldlocation_delete_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="sportsfieldlocation",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="sportsfieldlocation",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="field_images/",
                verbose_name="Field Image",
            ),
        ),
    ]
