# Generated by Django 5.1.4 on 2025-01-22 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0005_booking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="date",
            field=models.DateField(verbose_name="Booking Date"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="duration",
            field=models.IntegerField(verbose_name="Duration (hours)"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="locations.sportsfieldlocation",
                verbose_name="Sports Field",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="time",
            field=models.TimeField(verbose_name="Start Time"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
