# Generated by Django 5.1.4 on 2025-01-22 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0007_sportsfieldlocation_average_rating_favorite_rating"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favorite",
            options={"verbose_name": "Favorite", "verbose_name_plural": "Favorites"},
        ),
        migrations.AlterModelOptions(
            name="rating",
            options={"verbose_name": "Rating", "verbose_name_plural": "Ratings"},
        ),
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together=set(),
        ),
    ]
