# Generated by Django 5.1.4 on 2025-01-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0008_alter_favorite_options_alter_rating_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sportsfieldlocation",
            name="requires_payment",
            field=models.BooleanField(
                default=False,
                help_text="Check if this field requires payment to use.",
                verbose_name="Requires Payment",
            ),
        ),
    ]
