# Generated by Django 5.1.4 on 2025-01-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0009_sportsfieldlocation_requires_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="sportsfieldlocation",
            name="price_per_hour",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Specify the hourly price if the field requires payment.",
                max_digits=6,
                null=True,
                verbose_name="Price Per Hour",
            ),
        ),
    ]
