# Generated by Django 5.1.4 on 2025-01-27 07:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0010_sportsfieldlocation_price_per_hour"),
    ]

    operations = [
        migrations.AddField(
            model_name="sportsfieldlocation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created At",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sportsfieldlocation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
    ]
