# Generated by Django 5.1.4 on 2025-01-27 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0011_sportsfieldlocation_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sportsfieldlocation",
            name="favorites",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorite_sports_fields",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_entries",
                to="locations.sportsfieldlocation",
            ),
        ),
    ]
